version: '3.8'

services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.react
      args:
        - NODE_ENV=development
    ports:
      - "80:3000"
    volumes:
      - .:/opt/react_app/app
    environment:
      - NODE_ENV=development

volumes:
  notused:
